
Васю назначили завхозом в туристической группе и он подошёл к подготовке ответственно, составив справочник продуктов с указанием калорийности на 100 грамм, а также содержание белков, жиров и углеводов на 100 грамм продукта. Ему не удалось найти всю информацию, поэтому некоторые ячейки остались незаполненными (можно считать их значение равным нулю). Также он использовал какой-то странный офисный пакет и разделял целую и дробную часть чисел запятой. Таблица доступна по ссылке https://stepik.org/media/attachments/lesson/245290/trekking1.xlsx

Вася хочет минимизировать вес продуктов и для этого брать самые калорийные продукты. Помогите ему и упорядочите продукты по убыванию калорийности. В случае, если продукты имеют одинаковую калорийность - упорядочите их по названию. В качестве ответа необходимо сдать названия продуктов, по одному в строке.

In [10]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_excel("https://stepik.org/media/attachments/lesson/245290/trekking1.xlsx")
df

,Unnamed: 0,ККал на 100,Б на 100,Ж на 100,У на 100
0,Сухофрукты,548.0,12.8,40.8,32.4
1,Каша Быстров,334.0,8.6,4.8,64.0
2,"Балык ""Королевский""",170.0,25.0,8.0,NaN
3,"Колбаса с/к ""Еврейская полусухая""",481.0,19.0,45.0,NaN
4,Суп гороховый с копченостями,390.0,16.0,11.0,52.0
5,Суп томатный с рисом,205.5,4.7,1.3,42.2
6,Говядина Кронидов,213.0,15.0,17.0,NaN
7,Свинина Кронидов,349.0,13.0,33.0,NaN
8,Рис пропаренный Увелка,350.0,8.0,1.0,78.0
9,Крупа гречневая,360.0,13.0,2.0,72.0
10,Капеллини Макфа,344.0,12.5,1.3,70.5
11,Сухарики ржаные Finn Crisp,347.0,10.0,2.6,61.0
12,Козинак арахисовый,520.0,15.0,26.0,55.0
13,Козинак подсолнечный,530.0,14.0,37.0,36.0
14,Шоколад молочный какао,601.0,7.0,43.0,46.0
15,Шоколад молочный миндаль,574.0,7.7,38.2,49.5
16,Шоколад ремесленный,540.0,10.8,37.8,37.1
17,Сыр Маасдам,370.0,25.0,30.0,NaN
18,Сыр Гауда,338.0,26.0,26.0,NaN
19,Сыр Чеддер,369.0,23.5,30.5,NaN
20,Сухарики ржаные с семечками,451.0,17.3,16.0,59.5
21,"Хлебцы льняные ""Тайские""",507.0,19.0,39.0,20.0
22,Хлебцы льняные Морские,436.5,14.1,29.0,1.5
23,Паутина,12.0,NaN,NaN,NaN
24,Хлебцы с чесноком и луком,212.0,7.9,1.3,43.3
25,Говядина сублимрованная,474.0,73.0,20.0,NaN
26,Свинина сублимрованная,543.0,58.0,35.0,NaN
27,Борщ Московский Галагала,360.0,15.0,10.0,52.0
28,Суп-гуляш галагала,382.0,15.0,10.0,55.0
29,Суп куриный с картофелем галагала,390.0,15.0,12.0,56.4
30,Суп говяжий с картофелем галагала,390.0,12.2,12.0,56.4
31,Суп гороховый с копченостями галагала,390.0,16.0,11.0,52.0
32,"Суп-харчо ""Острый""",370.0,13.5,10.0,55.6
33,Картофель сушеный,333.0,6.0,74.0,NaN
34,Омлет с грибами галагала,526.0,43.0,30.0,4.7
35,Омлет с копченостями галагала,544.0,45.0,30.0,4.7
36,Кус Кус,336.0,12.7,0.6,77.4

In [17]:
df = df.sort_values(by = ['ККал на 100', 'Unnamed: 0'],ascending=[False,True])
df.head()

                       Unnamed: 0  ККал на 100  Б на 100  Ж на 100  У на 100
14         Шоколад молочный какао        601.0       7.0      43.0      46.0
15       Шоколад молочный миндаль        574.0       7.7      38.2      49.5
0                      Сухофрукты        548.0      12.8      40.8      32.4
35  Омлет с копченостями галагала        544.0      45.0      30.0       4.7
26         Свинина сублимрованная        543.0      58.0      35.0       NaN

In [18]:
with open('answer.txt','w') as f:
    [f.write(i+'\n') for i in df["Unnamed: 0"]]